### PR TITLE
Checkout: do not show bundled products as "Selected add-ons" in questions step

### PR DESCRIPTION
**Pull request by julianrother**

### CODE REVIEW

**Review by wiffbi — APPROVED** [review]
Looks good and works as intended. Thanks!

**Comment by raphaelm** [comment]
Hi @julianrother, we're only waiting for the CLA formalities on this, do you plan to sign it so we can move forward? Thanks again for the PR :)

**Comment by julianrother** [comment]
> Hi @julianrother, we're only waiting for the CLA formalities on this, do you plan to sign it so we can move forward? Thanks again for the PR :)

Sorry for the delay! I've now sent you the CLA.

**Comment by raphaelm** [comment]
@cla-bot[bot] check

**Pull request merged**
