### PR TITLE
Provide hidpi versions of logos and product pictures

### PR DESCRIPTION
**Pull request by stapelberg**
The idea is to provide a 200% and 300% version for hi-dpi mobile devices, tablets and laptops.

### CODE REVIEW

**Comment by raphaelm** [comment]
Hmm. hidpi is nice of course and I'd probably merge this for images on the web, but I'm not sure it's worth it for emails. Our email stack will convert these pictures to attachments, so this – especially if the logo contains a photo – can lead to *significantly* larger emails which is bad for deliverability. I'm not sure that's worth the effect.

**Comment by stapelberg** [comment]
> Our email stack will convert these pictures to attachments, so this – especially if the logo contains a photo – can lead to _significantly_ larger emails which is bad for deliverability. I'm not sure that's worth the effect.

Fair point. Maybe using an SVG logo is a better choice for emails. 

Either way, I have removed the email srcset change from this PR. Please take another look :)

**Comment by raphaelm** [comment]
> Fair point. Maybe using an SVG logo is a better choice for emails.

Yeah… but email is such a broken ecosystem, I don't wanna bet on the SVG implementations of some outlook version still used in large companies.

> Either way, I have removed the email srcset change from this PR. Please take another look :)

I updated the PR and added `srcset` to some some more places for consistency :)

**Review by ser8phin — APPROVED** [review]
Looks good. I agree with mail being a bit… difficult.
`srcset` is widely supported and I additionally tested it out with different settings and devices, so :+1:

**Comment by raphaelm** [comment]
I needed to revert this for now, unfortunately. We have many organizers who uploaded a picture with a size of exactly 1170px, since that is what we recommended so far. Since our thumbnailer only scales down, not up, the 2x image is still 1170px wide. At least Firefox (I did not test other browsers) at 2x resolution will however not check that and always scale down the picture by factor 2. After that, it is displayed to small.

If we still want this feature, we'd need to do it conditionally on the size of the available source picture in some way? Sounds quite tedious.

**Comment by stapelberg** [comment]
Thanks for letting me know. It was worth a shot. I might just go the SVG route for our case instead.

**Comment by wiffbi** [comment]
I’d love to add „better“ sized images. One problem with fixed px-values for sizing though also would be, that one could not upload high-res images that are to be displayed only as smaller images – e.g. I uploaded an event_logo in 400 x 100 px size. If I upload this as high-res in e.g. 1200 x 300 px, then currently the event logo would be scaled to a width of 1170px (if full_width setting is used, otherwise it would be scaled to 120 height). Not what I intended. Due to this, uploading high-res images would only work for full-width images – not ideal, but IMHO a okayish tradeoff.

As a side-note: especially event-logo is super tricky. When using a background other than pure white, it is shown as 1170 and page-content is set to 1120px width. If a pure white background is used, the image is scaled to 1140px and the page-content is set to match 1140px. The event-logo in 1140px on white background still uses the 1170px-thumb. Not ideal.

Not sure how to proceed. Maybe some kind of thumb-operator to force upscale as well? E.g. like imagemagick with the `<`, so `event_logo|thumb:'2340x5000<'`.

**Pull request merged**
