### PR TITLE
[WIP] Fix #447 -- Sendmail plugin: Create new mail based on an old one

### LINKED ISSUE #447: Sendmail plugin: Create new mail based on an old one
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at support@pretix.eu. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Python or Django development or who never contributed to Open Source before. We'd like to ask people with wide experience in these areas to leave this issue to beginners. Thanks! (If you want something more advanced, just drop us a line, we'll find something :wink:)

## How to get started

First of all, you need pretix running locally on your machine. We have a guide on the developer installation [over here](https://docs.pretix.eu/en/latest/development/setup.html). Play around with it and get a feeling for what pretix is and how it works :) Try to find the places in the interface mentioned in this issue where something needs to change. Maybe try to find the same places in the code? Just searching for characteristic words can be a powerful tool to find your way around.

## What this is about

If you create an event and then (under Settings > Plugins) activate the Sendmail plugin, there will be a new navigation option allowing you to send emails to everyone who ordered a ticket. Thanks to @FlaviaBastos, there is also a navigation item showing you the history of all mails sent through this feature. It would be nice if this history would include a button that allows you to create a new mail *based* on the old one, i.e. pre-fill the sendmail form with the contents from that time.

## How to do this

Find a way to pass the data around to the form. I believe the best way is to create a link in ``pretix/plugins/sendmail/templates/pretixplugins/sendmail/history.html`` that includes the ID of the log entry in a query parameter to the sending view (defined in ``pretix/plugins/sendmail/views.py``). I suggest that you shortly read up on how our [log objects](https://docs.pretix.eu/en/latest/development/implementation/logging.html) work. You can then modify the ``get_form_kwargs`` method of ``SenderView`` to pass the correct [initial values](https://docs.djangoproject.com/en/1.10/ref/forms/api/#dynamic-initial-values) to the form.

## I want to give it a try!

You're still reading, nice! If you want to try working on this, please comment below, so everyone else knows this is being looked at and can search for a different place to contribute. 

First, [fork](https://github.com/pretix/pretix/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier) and prepare your pull requests. There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). We're excited to see your pull request! 

And don't forget: If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

### PR DESCRIPTION
**Pull request by asv-hungvt**
https://github.com/pretix/pretix/issues/447

PR for creating new mail based on an old one

### CODE REVIEW

**Comment by asv-hungvt** [comment]
hi @raphaelm ,

I am having trouble while installing pip on windows.

Is it possible to setup the environment in windows or it should be an Unix? If it must be an Unix, what distro you would recommend?

**Comment by raphaelm** [comment]
Hi @asv-hungvt, I'll look at your code later, might be a bit of delay as I'm currently travelling.

Regarding Python 3.6, you can try "python -m venv" instead of pyvenv. pretix should work fine from Python 3.4 through to 3.6. Let me know if you have any more problems.

**Comment by raphaelm** [comment]
Somehow you only pushed an empty commit, was that on purpose?

**Comment by asv-hungvt** [comment]
Oh yes, it is just in case. I'm setting the project on Debian now and I think it will take awhile. I'll start as soon as I finish the setup :)

**Comment by raphaelm** [comment]
> Oh yes, it is just in case. I'm setting the project on Debian now and I think it will take awhile. I'll start as soon as I finish the setup :)

Sure. Let me know if you have any problems. Windows should work as well, but Debian surely works fine, our servers run Debian as well ;)

**Comment by asv-hungvt** [comment]
I have finished the setup on Debian and the project run really fine.
I will start the issue now :D

**Comment by asv-hungvt** [comment]
Hi @raphaelm ,

Itried to findout where to add user emails to send but there was no luck. Can you show me the detail?

I also enabled the plugin and followed this instruction https://docs.pretix.eu/en/latest/development/setup.html#working-with-mails
email

**Comment by raphaelm** [comment]
Hi,

I'm not sure if I understand your question correctly. In the menu on the left (or the top, if your display is to small), you should see a link "send emails" that allows you to send emails and view emails that you sent  before. The task is, to make it possible to copy content from the old emails to the form for a new email. You should not automatically send that email, just prefill the form with it.

Cheers
Raphael

**Comment by asv-hungvt** [comment]
Hi @raphaelm ,

I will briefly describe what I understand your solution so far;
When we open a existed email, there will be a link which we can click to create a new mail, and we will pass the old email content to the new one by passing the email content which we get from the log object and init the new mail in the  get_form_kwargs method
Please correct me if I am wrong.

I also need to know how to send a mail to a customer in order to test the copy mail content.  I followed the steps to create a product, added its quotas, order the product and send mail to the pending order customers but I stucked at adding the payment method for the product. 
Can you show me how to add the payment method?

Cheers and regards,
Hung

**Comment by raphaelm** [comment]
> When we open a existed email, there will be a link which we can click to create a new mail, and we will pass the old email content to the new one by passing the email content which we get from the log object and init the new mail in the get_form_kwargs method using request.session.get to get the content of the old mail

I'm not sure why you want to use ``request.session`` there, but otherwise correct. As a simple solution I would

* Include the ID of the ``LogEntry`` into the link to the sending form as a GET parameter, e.g. ``/control/event/orga/event/sendmail/?from_log=42``
* Read this in ``get_form_kwargs`` from ``self.request.GET``, retrieve the ``LogEntry`` and prefill the form  by constructing a proper [``initial``](https://docs.djangoproject.com/en/1.11/ref/forms/fields/#initial) dictionary
* Done :)

> I also need to know how to send a mail to a customer in order to test the copy mail content. I tried the pre-configured event but I stucked at adding the payment method for the big event 2018.
> Can you show me how to add the payment method?

Uhm, you might need to go to "Settings" > "Plugins" in your event and activate e.g. the Banktransfer plugin. Then go to "Settings" > "Payment" and activate it. No further config required :)

**Comment by asv-hungvt** [comment]
Hi rephaelm,

When I got the ID and retrieve the LogEntry, the message showed that there are 10 entries. I thought it would be 1 entry only. 

The code was:
```
from_log_id = self.request.GET.get('from_log)
LogEntry.objects.get(object_id=from_log_id) // it shows 10 records here
```
How will I get the object which I need by using the given id?

Another issue, in the views.py, I add a field send_url to refer to the url when we use to compose a new mail `/control/event/orga/event/sendmail/` and pass it to the history.html and then concat with the mailid to produce the `/control/event/orga/event/sendmail/?from_log=42.` I wonder is there any other solution which we can use directly the url in the template file instead of the way I am doing now?

**Comment by raphaelm** [comment]
> When I got the ID and retrieve the LogEntry, the message showed that there are 10 entries. I thought it would be 1 entry only.

Ah. If you look at the ``LogEntry`` model closely, ``object_id`` is the ID of the object the log is *attached* to. For example, if the log represents a change to an order, that's the ID of the order. If it represents a change to an event, it's the ID of the event (like in this case probably). Of course, multiple logs can be attached to the same event. The id of the *log itself* is just ``id``, not ``object_id``. You can't see it in the model code, because Django adds an ``id`` field automatically to all models where no other primary key is specified.

> Another issue, in the views.py, I add a field send_url to refer to the url when we use to compose a new mail /control/event/orga/event/sendmail/ and pass it to the history.html and then concat with the mailid to produce the /control/event/orga/event/sendmail/?from_log=42. I wonder is there any other solution which we can use directly the url in the template file instead of the way I am doing now?

I can't look at the code since you did not push it, but from what you describe I think it's okay-ish. But you don't even need code in the view for that, you can do that directly in the template, e.g.:

```
<a href="{% url "plugins:sendmail:send" organizer=request.event.organizer.slug event=request.event.slug %}?from_log={{ log.id }}">…</a>
```

I think thats both the easiest and cleanest way.

**Comment by raphaelm** [comment]
I'll close this as we have the other PR now :)

**Pull request closed without merging**
