### PR TITLE
Unify spelling of 'canceled' - #187

### PR DESCRIPTION
**Pull request by FlaviaBastos**
Switching 'cancelled' (double 'L') to 'canceled' (single 'L') across all files.

#187

I skipped all `src/pretix/base/migrations/*` files (I understand that these files are overwritten when new migrations are done, but I'm not sure about this :confused: ). Please let me know if they need to be included.

### CODE REVIEW

**Comment by raphaelm** [comment]
Hey :) Looks good to me so far! Only one suggestion: Could you revert the changes in ``src/static/typeahead/typeahead.bundle.js``? That code is not by us but part of [typeahead.js](https://twitter.github.io/typeahead.js/) and this will lead to confusion if we ever update that library.

**Comment by FlaviaBastos** [comment]
Sure! Just... hm... :flushed: any recommendation on how I can revert this file back - 'git speaking'? :grin: I've been reading about `git revert` but that seems to affect the whole commit, not just the one file. Is this right? 
Or should I just manually track the changes I made and undo them?

**Comment by FlaviaBastos** [comment]
I found something that seems to fit my case ([from here](http://stackoverflow.com/questions/2733873/reverting-a-single-file-to-a-previous-version-in-git)):

> you'll be able to find the SHA1 (hash) of the commit with the version of the file you want. Now, all you have to do is this:
> 
> # get the version of the file from the given commit
> `git checkout <commit> path/to/file`
> # and commit this modification
> `git commit`

I guess I will try this.

**Comment by raphaelm** [comment]
Yes, that is exactly what I just wanted to suggest :) If you do ``git commit --amend`` and then push with ``-f``, it will even squashed into the same commit so that there is just one single commit in the end.

**Comment by FlaviaBastos** [comment]
Did it work? :open_mouth: What is the emoji for sweaty-shaky hands?? :laughing: 
I was stuck with a typo.... :rage:

**Comment by raphaelm** [comment]
Yes it worked :) Thank you very much!

**Pull request merged**
