### PR TITLE
Upgrade to Django 1.11

### PR DESCRIPTION
**Pull request by rixx**
WIP! Needs at the very least a `django-i18nfield` release.

### CODE REVIEW

**Comment by raphaelm** [comment]
Thank you for starting this! New django-i18nfield 1.0.1 is ready, but PyPI currently does not let me upload :\ Could you identify any other blockers? The major change in 1.11 is form rendering, have you tested if our forms run still fine?

Tests did not run because you caused a few syntax errors when removing the ``Context`` objects.

**Comment by rixx** [comment]
I saw the syntax error but I figured I'd just touch everything when i18nfield was ready anyways. I didn't look much further, but all of the other upgrades in the production requirements are definitely necessary aswell. Ping me when you've got i18nfield 1.0.1 ready and I'll fix up the rest?

**Comment by raphaelm** [comment]
i18nfield 1.0.1 is released by now :)

**Comment by raphaelm** [comment]
Note to self: I'm currently doing something with ``AddOnsForm`` that probably needs to be re-done after this update.

**Comment by raphaelm** [comment]
See also #481

**Comment by raphaelm** [comment]
This looks fine to me know

**Pull request merged**
