### PR TITLE
Add install documentation for Kubernetes

### PR DESCRIPTION
**Pull request by Techwolf12**
I created a Helm Chart (Kubernetes package configuration) for Pretix using the official Docker image.

It is community managed, so I added a part of no support from the Pretix core team. Even then, I think it is a nice addition to include it on the documentation page.
You can view the current chart on [ArtifactHub](https://artifacthub.io/packages/helm/techwolf12/pretix)

The Helm chart automatically runs a migration container on upgrade, has a CronScheduler build in, and can run any number of web or worker instances. It also comes bundled with Postgresql and Redis for an easier setup.

CLA is signed and in the pretix support inbox.

### CODE REVIEW

**Comment by Techwolf12** [comment]
Screenshot of Kubernetes resources from my dev machine:

image

Seems to be working quite nicely! Also running this in production now

**Comment by Techwolf12** [comment]
@cla-bot check

**Comment by raphaelm** [comment]
@cla-bot check

**Comment by Techwolf12** [comment]
Completely understand, I made a new PR for the community install guide page!

**Pull request closed without merging**
