### PR TITLE
Implement #623 docker-compose

### PR DESCRIPTION
**Pull request by agowa338**
A working docker compose setup.

I also would recommend separating the docker-compose from the pretix repository into pretix/pretix-docker-compose for example, so this repository pretix/pretix can be included as git submodule and would not require copying files from other folders before build.

Implements: #623

### CODE REVIEW

**Comment by mdehollander** [comment]
I tested this installation procedure on a cloud instance at hetzner and it works smoothly.

However, I get mixed languages in the notification emails when I enable more languages. This does not happen on the pretix.eu hosted version, so I think it has something to do with the configuration in this docker installation. More info here: https://github.com/pretix/pretix/issues/1058. Does anyone of you tried this as well and experiences the same?

**Comment by agowa338** [comment]
@mdehollander Does this happen with the current version in the branch, too? I've not changed anything that would impact that. I've not changed anything in the current pretix codebase.

**Comment by raphaelm** [comment]
I agree that this should be a separate repository.

I'm not sure if it's wise to have it under the pretix organization, since we're not capable of supporting it properly (since we don't user docker compose ourselves), but maybe we can add it nevertheless. I created an empty repository which you can do a PR against :) https://github.com/pretix/pretix-docker-compose

**Comment by raphaelm** [comment]
Ah, also: If it isn't too much trouble, could you consider replacing mariadb with postgresql? It just is the better database ;) :elephant:

**Comment by agowa338** [comment]
@raphaelm Can you please add a README.md to the new repository? Without it Github does not allow me to fork, nor to create a pull request.
Also I use mariadb, because I use it all the time and I don't know why postgresql should be better. Is there anything I missed futurewise, why postgresql should be prefered?

**Comment by raphaelm** [comment]
> @raphaelm Can you please add a README.md to the new repository? Without it Github does not allow me to fork, nor to create a pull request.

Done!

> Also I use mariadb, because I use it all the time and I don't know why postgresql should be better. Is there anything I missed futurewise, why postgresql should be prefered?

It's a long, and obviously opinionated story. Historically, PostgreSQL has a reputation of favoring correctness (transaction safety!) over speed, where MySQL often made the trade-off the other way. PostgreSQL handles Unicode (Emojis!) a lot better and today, PostgreSQL tends to be faster (not in all cases, but as far as we see for pretix) and supports many advanced features better (like JSON data types, that we started using in pretix 2.2, but also a lot more stuff like geospatial support, functional indexes, …). At the same time, PostgreSQL has arguably better community support and is faster to add more features and improvements. Also, lots of new features are very different on MariaDB vs MySQL (like JSON fields) which makes it hard to support both of them. pretix will continue support MariaDB/MySQL going forward and we have no specific plans on stopping that, but we do see the possibility of adding features that will only work on PostgreSQL. Therefore, if we'd start giving people something like docker-compose that just installs pretix without much manual effort, I'd suggest we go for the recommended database option directly :)

**Pull request closed without merging**
