### PR TITLE
Add empty cart button #161

### PR DESCRIPTION
**Pull request by FlaviaBastos**
Add 'Empty Cart' button to cart.
Add test_remove_all to tests

One note: I added a new view `CartRemoveAll` but the only difference from `Cart Remove` is the success message.... Is that ok or are they too similar to have both?

### CODE REVIEW

**Comment by raphaelm** [comment]
Hi Flavia,

I like very much how you built this re-using the code from ``CartRemove`` and just passing in values for all lines. I didn't even think of that ;) I see two ways to nicely get around duplicating code introduced by this:

1. Make ``CartRemoveAll`` a subclass of ``CartRemove`` that only defines the success message and inherits all other methods from its parent.

2. Drop the new view completely and improve ``CartRemove.get_success_message`` in a way that selects between the two messages depending on whether any more cart items exists: ``if CartPosition.objects.filter(cart_id=self.request.session.session_key).exists(): ...`` This will then also show the "is now empty" message if the user just deletes the last item manually, which is perfectly fine.

I'm slightly in favor of option two. What do you think?

We'll probably run into another problem here: There is the possibility to have multiple items in the cart that are to the same item and variation but are *not* grouped together in one cart line. This can happen if their price differs (e.g. because one has a voucher attached) or if there are questions defined and filled in etc. With your code, this would lead to the duplicate definition of a form field (which is fine in HTML, it will just get send twice) but probably won't be parsed correctly by ``_items_from_post_data()``. If you want, you can try to patch ``_items_from_post_data`` for this, but it probably won't be easy. I can do that as well. But I'd love for this PR to include at least a (failing) test that checks this so that we don't forget it and that we know it is solved once it is :) You can decorate that test with ``@pytest.mark.xfail`` ("expected failure") such that this PR stays green ;)

Best
Raphael

**Comment by FlaviaBastos** [comment]
>  just passing in values for all lines. I didn't even think of that

Hm! Now I am curious: what would be your go to approach?

> I'm slightly in favor of option two. What do you think?

Yeah, let's go with 2. I will see how far I can go and I will let you know if I get stuck. I will also add the failing test as you requested. 

Thanks for the feedback! :)

**Comment by raphaelm** [comment]
> Hm! Now I am curious: what would be your go to approach?

I would have probable made a view that simply executes ``CartPosition.objects.filter(cart_id=request.session.session_key).delete()``. Now that I've written that down, it looks very simple. But option two of the above doesn't add any new views and no new code that touches CartPositions, I like that.

**Comment by FlaviaBastos** [comment]
I made the modifications you suggested above (implementing 2) and I can see the issue you pointed out: If I have a discounted t-shirt (with a voucher) and a regular priced t-shirt in the cart, the empty cart doesn't remove both. :unamused: 
But now I'm having a hard time writing a failing test. They all pass! :stuck_out_tongue: I am missing something for sure. Here's what I have now:
```
    def test_remove_all_same_variation_different_price(self):
        CartPosition.objects.create(
            event=self.event, cart_id=self.session_key, item=self.shirt, variation=self.shirt_red,
            price=14, expires=now() + timedelta(minutes=10)
        )
        v = Voucher.objects.create(item=self.shirt, variation=self.shirt_red, price=Decimal('10.00'), event=self.event)
        self.client.post('/%s/%s/cart/add' % (self.orga.slug, self.event.slug), {
            'variation_%d_%d_voucher' % (self.shirt.id, self.shirt_red.id): v.code,
        }, follow=True)
        response = self.client.post('/%s/%s/cart/remove' % (self.orga.slug, self.event.slug), {
            'variation_%d_%d' % (self.shirt.id, self.shirt_red.id): '2',
        }, follow=True)
        doc = BeautifulSoup(response.rendered_content, "lxml")
        self.assertIn('empty', doc.select('.alert-success')[0].text)
        self.assertFalse(CartPosition.objects.filter(cart_id=self.session_key, event=self.event).exists())
```
Can you help, please?

**Comment by raphaelm** [comment]
Heh. You somehow outsmarted yourself when writing that test :wink:
```
        response = self.client.post('/%s/%s/cart/remove' % (self.orga.slug, self.event.slug), {
            'variation_%d_%d' % (self.shirt.id, self.shirt_red.id): '2',
        }, follow=True)
```
works, because CartRemove is clever enough to work with the ``2``. Your template, however, will generate something different. It won't generate a value of ``2`` but two values of ``1``:
```
<input type="hidden" name="variation_1_1" value="1">
<input type="hidden" name="variation_1_1" value="1">
```
So the test would probably (I didn't test this) need to look like:
```
        response = self.client.post('/%s/%s/cart/remove' % (self.orga.slug, self.event.slug), {
            'variation_%d_%d' % (self.shirt.id, self.shirt_red.id): ('1', '1')
        }, follow=True)
```

**Comment by FlaviaBastos** [comment]
Where would you like me to go from here? Explore the `_items_from_post_data` and try to fix the issue I created :flushed: or do I leave it to you (you mentioned it will not be easy and I believe you!)?
If you prefer to take over the remaining part of this issue, then I guess I could look at #307 or #308 as you suggested... Thoughts?

**Comment by raphaelm** [comment]
It's not actually that hard to *change*, but its rather hard to *find* what to change, so I did it and refactored the method a bit on the way. Sure, have a look at the other issues, I'd suggest #307 :)

**Comment by FlaviaBastos** [comment]
Ah, nice! I see your code. 
I was a bit uneasy leaving things not working 100% :disappointed: Thanks for accepting my code anyway. :)
I will move to #307 then.

**Pull request merged**
