### PR TITLE
remove javascript URIs for CSP

### PR DESCRIPTION
**Pull request by FlaviaBastos**
This refers to issue #155 
I removed the inline javascript on the error pages and replaced them with external files but I'm not sure I placed them in the right place.
Also, I know that there is some meta tag changes that need to be done ([according to this](https://developers.google.com/web/fundamentals/security/csp/)) but was not sure how you wanted and if I should do it.
So I'm submitting this to get some feedback. :wink:

### CODE REVIEW

**Comment by raphaelm** [comment]
Hi! This looks good and is the correct way to do it. One minor thing: I think we can combine the JS files into a errors.js. There is no need.to have the browser load two files.

We don't need the metatags, they are just a different way to express what we already do with headers.

**Comment by FlaviaBastos** [comment]
Argh... I think I messed up the commit... :unamused:

**Comment by raphaelm** [comment]
Doesn't look that bad, it just has all three JS files in it :) Remove the two old ones and we're good to go :)

**Comment by FlaviaBastos** [comment]
What a mess.... so sorry about that... :disappointed: 
It looks like the two files are removed but hey, who knows! :laughing: 
@raphaelm you are very patient! Thanks!

**Comment by raphaelm** [comment]
Now all is perfect, thanks a lot! :)

**Pull request merged**
