### PR TITLE
Free price: Allow to suggest a different price than the minimum

### PR DESCRIPTION
**Pull request by raphaelm**
- [x] Data model
- [x] Backend
- [x] Product selection
- [x] Add-on selection
- [x] Add-on change dialog
- [x] Voucher redemption
- [x] Widget
- [x] API

### CODE REVIEW

**Review by wiffbi — APPROVED** [review]
Looks good.

One thing on variations I stumbled upon is: it uses the display_price for „starting at“. When opening the variations it might be irritating that that price is not shown as the suggestion is used to fill the input. Should we add some indicator for the min-value? We could e.g. extend the title-attribute used for the tooltip-thingie to „Modify price for <item>, at least <display_price>“.

**Review by wiffbi — APPROVED** [review]
Wonderful!

**Comment by c0de-bender** [comment]
@raphaelm @wiffbi Great, super nice to see this feature coming!

I was looking for it. I only found #1196 and wanted to push this issue, because I assumed Pretix cannot do it. Then I saw the `free_price_suggestion` branch in the git log mentioning this pull request. Very nice!

Note: #1196 can be closed then, I guess.

Question: Is this already tested and release-ready? I'd like to cherry-pick it and deploy and use it right away, if it's "safe".

**Comment by raphaelm** [comment]
> Is this already tested and "release-ready"? I'd like to cherry-pick it and deploy and use it right away, if it's "safe" to use.

It's tested and it's safe to use. However, I'd avoid cherry-picking commits that include database migrations. Applying them in the wrong order might need to chaos, if you're not very well-versed in django and know how to work around it. But it should be usually fine to run from the master branch in production for a while ;)

> Looking at the commit changes, I stumbled upon an addition in `doc/api/resources/item_variations.rst`:

Thanks!

**Comment by c0de-bender** [comment]
> > Is this already tested and "release-ready"? I'd like to cherry-pick it and deploy and use it right away, if it's "safe" to use.
> 
> It's tested and it's safe to use. However, I'd avoid cherry-picking commits that include database migrations. Applying them in the wrong order might need to chaos, if you're not very well-versed in django and know how to work around it. But it should be usually fine to run from the master branch in production for a while ;)
> 

That's great! :)

Thanks for the advice, too. I compared the current master with the last version tag and the database migration script in this commit was the only one so far, so I thought it's safe to cherry-pick. However, you're right that it's not good practice, so I'll stick to the commit the master is pointing to.

**Pull request merged**
