### PR TITLE
Allow rich text in product and category descriptions

### PR DESCRIPTION
**Pull request by FlaviaBastos**
Using [django-markup](https://django-markup.readthedocs.io/en/latest/installation.html) to allow rich text in product and category descriptions.
Added django-markup to requirements and setup

#51

### CODE REVIEW

**Comment by raphaelm** [comment]
That is awesome! Don't care about travis failing with "no build output received for 10 minutes", that is selenium talking, I *really* need to get rid of this. I'm testing this manually and it works great.

One caveat: Apparently, not only ``django-markup`` is required, but the ``markdown`` package also needs to be installed explicitly. Would you like to address this?

If you *want* to, you can also add markdown to the recently added ``frontpage_text`` (see 60c1048), but if not I can do this as well after this is merged.

**Comment by FlaviaBastos** [comment]
Hi @raphaelm 
Oh, my bad... I forgot about 'markdown' :blush: It's fixed now. Sorry about that! And I added my name to authors - thanks! :)

I tried to add markdown to the frontpage_text but I got an error when manually testing the page (even before changing the code). I reported the issue (#160) so you can take a look and confirm (it could be something wrong with my setup too...). Anyway, I know what needs to be done to add markdown support to the frontpage but I didn't want to do it in the dark, without testing. 

Will send a push request shortly.

**Comment by raphaelm** [comment]
Hey @FlaviaBastos, I'm just gonna merge this now so it is in here before my holiday. If you want to add the frontpage text thing when we got #160 resolved, you are invited to do so; if you don't, I'm gonna do it, it probably boils down to a one-line change in the template. Thanks a lot for taking your time to do this! :)

**Comment by FlaviaBastos** [comment]
Hi, @raphaelm 
I will poke around issue #160 as you suggested and will update with my findings.

I will also try to find out what's going on with my setup (local tests failing, etc). Maybe when I get this running smoothly I can grab other issues. :)

Have a nice holiday!

**Pull request merged**
