### PR TITLE
Add order code to pdf and to ticket settings #148

### PR DESCRIPTION
**Pull request by FlaviaBastos**
Add order code to tickets generated by PDF
Add order code to ticket settings in control

#148

### CODE REVIEW

**Comment by raphaelm** [comment]
Hi! Thanks a lot! One direct comment, before I've actually tested it:
Could you replace ``"%s %s" % ('Order code:', str(order.code))`` with ``_('Order code: {code}').format(code=order.code)``? This way, the string "Order code" can later be translated to other languages.

**Comment by FlaviaBastos** [comment]
Sure! Just to confirm: the underscore before the opening parenthesis on `_('Order code: {code}').format(code=order.code)` is expected to be there, right? I'm not familiar with that...( I think)

**Comment by raphaelm** [comment]
Exactly! If you look at the imports at the top of the file, the function ``ugettext_lazy`` is imported with the name ``_``. ``ugettext_lazy`` is basically a magic function that takes a string and returns a translated version if one exists. Because one needs that function all the time and it is tedious to type it out, it is convention to rename it to a single underscore.

If you are interested, the matching docs are here: https://docs.djangoproject.com/en/1.10/topics/i18n/translation/
Be warned, this is a rather complicated matter as it follows the standard of GNU gettext, a nearly ancient translation tool ;)

**Comment by FlaviaBastos** [comment]
Thank you so much for the explanation!

**Comment by raphaelm** [comment]
Works like a charm, thanks a lot! :)

**Pull request merged**
