### PR TITLE
Add markdown support to frontpage

### PR DESCRIPTION
**Pull request by FlaviaBastos**
Adding markdown support to frontpage. 

This expands markdown support implemented on issue #51.

### CODE REVIEW

**Comment by FlaviaBastos** [comment]
Hmm... I don't know how to separate the very last commit from the rest. Everything was already merged except for the last one: [support markdown on frontpage](https://github.com/pretix/pretix/pull/168/commits/6e9a1562a3edea2be43e5f6e89b22d6aab33f81b)

I'm new to development (and Git and GitHub) and will appreciate directions.

**Comment by rixx** [comment]
Ah, hm, this might get a bit tricky. I think the easiest way would be to for @raphaelm to hit "Squash and merge", to make all of this into a single commit with the appropriate message (of your last commit).

**Comment by rixx** [comment]
For future reference, you might want to work in feature branches - that is, one branch per feature or ticket you are working on. It helps isolating issues and is generally considered good practice. [This](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows) is a rather technical explanation of branching - if you have trouble with it, I'll try to find something more clear. Sadly, git is not the easiest tool to work with :(

For now, if you decide to work with a feature branch, please base it off the `origin/master` (the version of the main pretix repo):

```
git checkout 04ab016 
git checkout -b name_of_your_feature_branch
```

If you are interested in more, maybe ping me directly :)
git

**Comment by FlaviaBastos** [comment]
Thank you so much for the info @rixx! I will check the link you sent. Fair warning: I will probably have questions. :stuck_out_tongue_winking_eye:

**Comment by raphaelm** [comment]
Hey @FlaviaBastos,
I did not trust GitHub with merging this nicely after the branch confusion, so I merged it manually in 95159d2af581d41d4ba8c735e4a83260183db30d. @rixx tells me that he provided you with some information on how to continue. 

If you want to continue working on pretix, @rixx opened a lot of issues over the last couple of them. I marked a bunch of them as ``easy`` just a few minutes ago, but even some of the ones I did not mark as easy (like #173) might be possible -- if you are interested :)

**Comment by FlaviaBastos** [comment]
Hi, @raphaelm! 
Thanks for resolving this issue. I wouldn't be able to do it! And yes, @rixx provided me with excellent information on how to move forward with branches. Thank you both so much for all the help.

Also, I am really interested to stick around. I will have a look and check what I can take. :)

**Comment by raphaelm** [comment]
@FlaviaBastos Great to hear! Starting on wednesday I'll be on holiday once again until the 29th and @rixx will also be away for a couple of days at the end of this week, but please, if you have questions, do write us anyway, we'll answer as soon as we get to it :)

**Pull request closed without merging**
