### PR TITLE
Update pytest version and related packages

### PR DESCRIPTION
**Pull request by wiffbi**
Updated requirements to fix pytest-django to version 3.* as latest version 4.0.0 requires pytest==5.4, which currently breaks tests.

### CODE REVIEW

**Comment by raphaelm** [comment]
Thanks! When we discussed this previously, I understood that the only problem on pytest 5.4 was a "real" failure that has now been fixed. Did I understand that wrongly?

**Comment by wiffbi** [comment]
Sorry, for the missunderstanding: pytest 5.4 fails 1 Test and skipped 3. Also several RemovedInDjango40Warnings were emitted. I will look into this and use this branch to update.

**Comment by wiffbi** [comment]
Sorry for the confusion, all tests (except 3 skipped, 1 xfailed) pass with pytest 5.4. Updated requirements and setup.py to always use latest versions of pytest and pytest-django.

**Comment by raphaelm** [comment]
On CI, there seems to be a failure in pytest-rerunfailures, maybe we need to upgrade that package as well?

**Pull request merged**
