### PR TITLE
Consistently set default background PDFs on server, not client

### PR DESCRIPTION
**Pull request by raphaelm**

### CODE REVIEW

**Review by pc-coholic — CHANGES_REQUESTED** [review]
`pretix.multidomain.utils` seems to be missing in the commited files.

**Comment by raphaelm** [comment]
Oops, pushed. How the hell did this not break the CI :thinking:

**Comment by pc-coholic** [comment]
> Oops, pushed. How the hell did this not break the CI thinking

The CI did not run for some reason - only the CLA check :shrug:

**Comment by raphaelm** [comment]
I also reverted the change in style.py for safety, it's only 99% the same thing and I'm not sure enough it won't break anything

**Review by pc-coholic — APPROVED** [review]
LGTM :tada: 

Once the tests pass: :ship:

**Pull request merged**
