### PR TITLE
Hide add to cart button if no products active or no quantity left(#180)

### PR DESCRIPTION
**Pull request by vishalsodani**

### CODE REVIEW

**Comment by raphaelm** [comment]
Hey @vishalsodani  just for your information, I'm on vacation right now and will get back to this as soon as possible, but maybe not before next week. Thank you for your work!

**Comment by raphaelm** [comment]
Hi @vishalsodani thank you very much for this work!
However, I don't believe this behaves correctly for more than one item. Let's assume for a minute that there are two items of which the first one is available and the second one is not. In that case, in the first iteration of ``for item in items`` the ``display_add_to_cart`` flag will be set to ``True``, in the second iteration it will be overridden with ``False`` and is ``False`` in the end. Do I see this correctly? If so, a possible solution might be something like:

```
display_add_to_cart = display_add_to_cart or item.order_max > 0
```

**Comment by vishalsodani** [comment]
Hi @raphaelm You are absolutely right! I will fix and commit as per your suggestion.

**Comment by raphaelm** [comment]
Looks good now! Thank you very much for the contribution!

**Pull request merged**
