### PR TITLE
vouchers: allow deleting vouchers that are used on addon cartpositions

### PR DESCRIPTION
**Pull request by MaicoTimmerman**
Proposed fix for #2477.

I'm open to construct a test-case, if needed.

### CODE REVIEW

**Comment by raphaelm** [comment]
The bug seems valid, I'm hesitant if this is the best fix, will need to think about it briefly.

**Comment by MaicoTimmerman** [comment]
> The bug seems valid, I'm hesitant if this is the best fix, will need to think about it briefly.

For reference, according to [the docs ](https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.RESTRICT) the behaviour should remain the same, except the protection is lifted by delete ting the related object in the same action. Removing the non add-on CartPosition by itself should remain impossible.

**Comment by raphaelm** [comment]
Yes, I agree that from the docs it sounds like this is the solution. I'm hesitant with lifting this requirement on the model because I'm worried it might have unexpected consequences in other places, although I can currently not come up with any.

The reason I was surprised by this issue is mostly because we're already handling it here for single vouchers:

https://github.com/pretix/pretix/blob/069dd02ebc2847852daa8467fdffbc48dcd01411/src/pretix/control/views/vouchers.py#L246-L248

And here for bulk deletion:

https://github.com/pretix/pretix/blob/069dd02ebc2847852daa8467fdffbc48dcd01411/src/pretix/control/views/vouchers.py#L553-L554

I'd like to understand first why the issue shows up in the first place and I currently do not :D

**Comment by MaicoTimmerman** [comment]
I was also surprised this showed up when looking at the lines you mentioned, however Django does not rely on database foreign key constraints. Instead, Django checks for related objects itself by issuing `SELECT` statements. The logic is contained [here](https://github.com/django/django/blob/main/django/db/models/deletion.py).

With `PROTECT` the error is raised regardless of the related object also being deleted. With `RESTRICT` the related objects are actually inspected, to see if they are also being deleted.

To re-iterate the actual issue here, this only happens if we are deleting 2 simultaneous `CartPostion`. `CartPosition` 1 is a product using the voucher and `CartPosition` 2 is using the voucher and has `CartPosition.addon_to_id == 1`. When only one of both `CartPosition` are using the voucher, no errors is thrown.

If you which to retain `PROTECT`, I think we can also change the lines you mentioned to first delete the CartPositions that are add-ons and afterwards delete the non add-ons products. Although, I've not verified this.

**Comment by raphaelm** [comment]
> To re-iterate the actual issue here, this only happens if we are deleting 2 simultaneous CartPostion. CartPosition 1 is a product using the voucher and CartPosition 2 is using the voucher and has CartPosition.addon_to_id == 1. When only one of both CartPosition are using the voucher, no errors is thrown.

If that were correct, would not CartPosition 2 be already deleted first by `CartPosition.objects.filter(addon_to__voucher=self.object).delete() ` and then cartposition 1 is no longer referenced and can be deleted by `self.object.cartposition_set.all().delete() ` just fine?

Could it be that your case includes two different vouchers?

**Comment by MaicoTimmerman** [comment]
Right, so I think we've both missed the actually mistake. In the bulk deletion case, it actually says `OrderPosition`, not `CartPosition`!

**Comment by raphaelm** [comment]
Ooooh. This is bad, OrderPositions should obviously never be deleted (luckily, there is a .is_allowed() check that should prevent that).

**Pull request merged**
