### PR TITLE
Fix #448 -- Integrated PlaceholderValidator to MailForm at plugins/sendmail

### LINKED ISSUE #448: Auto-detect wrong placeholders in mail texts
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at support@pretix.eu. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Python or Django development or who never contributed to Open Source before. We'd like to ask people with wide experience in these areas to leave this issue to beginners. Thanks! (If you want something more advanced, just drop us a line, we'll find something :wink:)

## How to get started

First of all, you need pretix running locally on your machine. We have a guide on the developer installation [over here](https://docs.pretix.eu/en/latest/development/setup.html). Play around with it and get a feeling for what pretix is and how it works :) Try to find the places in the interface mentioned in this issue where something needs to change. Maybe try to find the same places in the code? Just searching for characteristic words can be a powerful tool to find your way around.

## What this is about

There are two places in pretix where the event organizer can configure texts for emails. First, in the event settings the templates for various emails can be changed. Second, if you activate the "Sendmail" plugin for an event, there will be a navigation option allowing you to send mails to all users.

In both of these cases, there is a set of placeholders specified in the ``help_text`` of the form fields that allows organizers to include text snippets that are generated differently for every user, for example a link to the order.

The sendmail plugin already has a preview feature, the email settings are currently getting one (#308 #438). However, to prevent organizers from making embarrassing mistakes by sending out emails with invalid placeholders, we should try to validate them.

## How to do this

Create a [validator class](https://docs.djangoproject.com/en/1.10/ref/validators/) that validates that only the placeholders are used in a field, that are allowed in this field. This will require a bit of thinking and maybe some tinkering with regular expressions, but I'm sure you can do it and if you have trouble on the way, we are here to help.

Then, add this validator with appropriate arguments to the appropriate fields of ``MailSettingsForm`` (``pretix/control/forms/event.py``) and ``MailForm`` (``pretix/plugins/sendmail/forms.py``).

## I want to give it a try!

You're still reading, nice! If you want to try working on this, please comment below, so everyone else knows this is being looked at and can search for a different place to contribute. 

First, [fork](https://github.com/pretix/pretix/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier) and prepare your pull requests. There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). We're excited to see your pull request! 

And don't forget: If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions

### PR DESCRIPTION
**Pull request by Alexeyisme**
Added class-based validator right to the forms.py at plugins/sendmail and integrated it in MailForm in same file.

### CODE REVIEW

**Comment by raphaelm** [comment]
Hi @Alexeyisme,

this looks good, you can go ahead on this route!

There is one thing I can currently think of that could be improved. The variable ``value`` is a complicated thing, namely an [I18nLazyString](https://django-i18nfield.readthedocs.io/en/latest/strings.html) that, if the event has multiple languages enabled, contain texts in more than one language. By calling ``str(value)``, it is converted to the active language, for example English. However, we of course would want to validate the content in **all** languages. You could for example try doing it like this:

```
for language, translated_value in value.data.items():
    # perform validation on translated_value
```

Cheers
Raphael

**Comment by Alexeyisme** [comment]
HI, @raphaelm!
That iteration would be cool, but when validator is applied to field, it takes and validates just each value from field as a string. So inside of validator `value` is just a string. One by one in each language each validation cycle.
Good thing: It means I don't need `str()` in `PlaceholderValidator` at all.
Not so good: I can not specify language name in field error messages.
One more: for some reason, field error messages are rendered "backwards" on page: 
```
Invalid placeholder(s): {BADGERINF}, {BADGERINF2}
Invalid placeholder(s): {BADGER}, {BADGER2}
Invalid placeholder(s): {BADENG}, {BADENG2}
```
when form field is rendered eng -> ger -> ger inf...

**Comment by raphaelm** [comment]
> That iteration would be cool, but when validator is applied to field, it takes and validates just each value from field as a string. So inside of validator value is just a string. One by one in each language each validation cycle.

Oh. That happens when I write without confirming what I say first :see_no_evil: 

> Not so good: I can not specify language name in field error messages.

We probably can't to anything here.

> One more: for some reason, field error messages are rendered "backwards" on page:

Interesting. This is probably somewhere deep in the forms logic, I don't think you need to deal with this.

**Comment by Alexeyisme** [comment]
Shall I now Integrate `PlaceholderValidator` to `MailSettingsForm` at (`pretix/control/forms/event.py`)?
Also: what do you think of `PlaceholderValidator` placement? May it be repeated or you have a special place where such things live?

**Comment by Alexeyisme** [comment]
Hi, @raphaelm!

While integrating `PlaceholderValidator` in `MailSettingsForm` found a typo in a `help_text`
{paymentinfo} instead of {payment_info}:

```mail_text_order_placed = I18nFormField(
        label=_("Text"),
        required=False,
        widget=I18nTextarea,
        help_text=_("Available placeholders: {event}, {total}, {currency}, {date}, {paymentinfo}, {url}, "
                    "{invoice_name}, {invoice_company}"),
        validators=[PlaceholderValidator(['{event}', '{total}', '{currency}', '{date}', '{payment_info}',
                                          '{url}', '{invoice_name}', '{invoice_company}'])]
    )
```

Can I correct it?

**Comment by raphaelm** [comment]
> May I now Integrate PlaceholderValidator to MailSettingsForm at (pretix/control/forms/event.py)?

Sure!

> By the way: what do you think of PlaceholderValidator placement? May it be repeated or you have a special place where such things live?

No, we should not repeat it. Maybe create a new ``pretix/base/forms/validators.py`` file?

> While integrating PlaceholderValidator in MailSettingsForm found a typo in a help_text
{paymentinfo} instead of {payment_info}:

Apparently, this is not a typo, but an inconsistency (we use paymentinfo in some places and payment_info in others). That's bad and we should get rid of it at some point, but for now, for *this* setting it seems to be the correct this way and just replacing it in the help_text won't work. See #467 as well.

**Comment by Alexeyisme** [comment]
Done!
I made a new `pretix/base/forms/validators.py` file as you said, and integrated `PlaceholderValidator` in both forms. Added import to `__init__.py` at `pretix/base/forms/`.

**Comment by Alexeyisme** [comment]
Looks like Travis doesn't like my PR. But it works on my local machine right now..

**Comment by Alexeyisme** [comment]
@raphaelm, is something wrong?
I checked forms locally. Validation works as expected. But looks like Travis CI has build problems.. why?

**Comment by raphaelm** [comment]
Hi @Alexeyisme, apparently, in some cases, ``value`` indeed is a ``LazyI18nString``, at least during tests. I can look into the reasons myself later or in the next days, you don't need to worry.

**Comment by raphaelm** [comment]
Hi,

I'll deal with the Travis issues. Your patch is good, thank you very much!

Congratulations on your first PR! :sparkles: 

Cheers
Raphael

**Pull request merged**
