### PR TITLE
feat: Add a docker compose file

### PR DESCRIPTION
**Pull request by ZPascal**
Hi community, I've added a docker-compose file to make the usage of pretix a bit easier.

### CODE REVIEW

**Comment by raphaelm** [comment]
Hi! Thanks for this! So far, we've rejected all proposals of this since once we have it, we need to maintain it, and since we don't use it ourselves, this is an additional burden. At the same time, this is at least the best attempt at it that we've had yet ;) So I'll try to find some time to think about this more.

**Comment by ZPascal** [comment]
Hi @raphaelm, du you have any news for me? Is it possible to merge the PR?

**Comment by raphaelm** [comment]
I did not have time to look into it yet. We are interested in this, but it's not a priority right now

**Comment by raphaelm** [comment]
Until the time we decide to publish an official compose file, the right place would be for this to be published somewhere else(tm) and linked here:
https://docs.pretix.eu/en/latest/admin/installation/community.html

**Comment by ZPascal** [comment]
@raphaelm I've prepared a separate [repo](https://github.com/ZPascal/pretix-docker-compose) to publish the `docker-compose` file for local development. How can I add it to the community section inside the documentation?

**Comment by raphaelm** [comment]
I've added it in 0c09cccd4 now!

**Comment by ZPascal** [comment]
@raphaelm Thank you.

**Pull request closed without merging**
